trigger:
- main

pool:
  vmImage: windows

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: install
    workingDir: '$(Build.SourcesDirectory)/hands-on-frontend'
- task: Npm@1
  inputs:
    command: custom
    workingDir: '$(Build.SourcesDirectory)/hands-on-frontend'
    customCommand: 'npm run build -- --prod'
